---
engines:
  rubocop:
    exclude_paths:
      - "config/test.yml"
    base_sub_dir: "test/baseDir"
  duplication:
    exclude_paths:
      - "config/test.yml"
    config:
      languages:
        - "typescript"
        - "javascript"
languages:
  css:
    extensions:
      - "-css.resource"
      # - "-scss.resource" # not sure if this even works for scss
exclude_paths:
  - ".bundle/**"
  - "spec/**/*"
  - "benchmarks/**/*"
  - "**.min.js"
  - "**/tests/**"
  - "**/*.md"
  - "storybook-static/**/*"
  - "src/styles/**/*"