# processors:
#   - stylelint-processor-html
extends: stylelint-config-standard
syntax: scss
plugins:
  - stylelint-scss
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  no-empty-source: ~
  block-no-empty: ~
  color-no-invalid-hex: true
  no-descending-specificity: null
  font-family-no-missing-generic-family-keyword: null
  comment-empty-line-before:
    - always
    - ignore:
        - stylelint-commands
        - after-comment

indentation:
    - 2
    - except:
    - value
max-empty-lines: 1
unit-whitelist: [ px, '%', em ]