name: CI Analysis
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: ESLint Plus
      uses: bradennapier/eslint-plus-action@v3
    - name: ESLint Annotate from Report JSON
      uses: ataylorme/eslint-annotate-action@1.2.0
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Easy Coding Standard Action
      uses: zingimmick/ecs-action@0.0.4
