name: Code Analysis
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: ESLint Annotate from Report JSON
      uses: ataylorme/eslint-annotate-action@1.2.0